name: iOS CI

on:
  push:
    branches:
      - main
      - develop
      - '**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Test
    runs-on: [self-hosted, macos, x86-64]
    env:
      SCHEME_NAME: TinyMeet-Staging
      PROJECT_PATH: TinyMeet.xcodeproj
      DESTINATION: generic/platform=iOS
      RUNNER_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          echo $RUNNER_PASSWORD | sudo -S xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Xcode build check
        run: |
          /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild \
            -project "$PROJECT_PATH" \
            -scheme "$SCHEME_NAME" \
            -destination "$DESTINATION" \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build_output
          path: build